### ISSUE TITLE
error: module 'Process' has no member named 'exec'

### ISSUE THREAD

**Issue by drmidnight** [oarrabi/Process#1]
Whenever I import and try to use 'Process.exec("blah blah")' with Guaka I'm given:
`error: module 'Process' has no member named 'exec'`

 All other "Batteries included" packages work fine.

**Comment by finestructure** [comment]
The problem is that `enum Process {` is not public. I've fixed this by going to the source as follows:

```
public enum Process {
```

**Comment by nsomar** [comment]
I submitted a pr #2 I'll merge it as soon as the test passes!
Thanks for raising it!!
