### ISSUE TITLE
Stray characters in stdout, stderr

### ISSUE THREAD

**Issue by finestructure** [oarrabi/Process#4]
When running commands with `echo` configuration I’m seeing stray characters in the console:

```
Stdout:
Login Succeeded
X�@Q�
Stderr:
```

I first noticed this also when reading from `RunResults.stdout` and trying to parse it. It looks like something is reading past EOF. I once got an entire extra line from another command in the output stream.

**Comment by finestructure** [comment]
I’ve just [added a test](https://github.com/feinstruktur/Process/commit/9e5dedb3f2db6f956725092e25bd0d624782652d) for this issue, although note that the failure is not visible in the test itself but in the tests console log.

```
$ swift test
Test Suite 'All tests' started at 2017-02-11 11:35:35.082
Test Suite 'ProcessPackageTests.xctest' started at 2017-02-11 11:35:35.083
Test Suite 'ProcessTests' started at 2017-02-11 11:35:35.083
Test Case '-[ProcessTests.ProcessTests testICanEchoOnlyTheCommand]' started.
Test Case '-[ProcessTests.ProcessTests testICanEchoOnlyTheCommand]' passed (0.001 seconds).
Test Case '-[ProcessTests.ProcessTests testItCanEchoBackNothing]' started.
Test Case '-[ProcessTests.ProcessTests testItCanEchoBackNothing]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testItCanEchoBackTheCommandOnly]' started.
Test Case '-[ProcessTests.ProcessTests testItCanEchoBackTheCommandOnly]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testItDoesNotEchoIfEmpty]' started.
Test Case '-[ProcessTests.ProcessTests testItDoesNotEchoIfEmpty]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testItDryExecutesLS]' started.
Test Case '-[ProcessTests.ProcessTests testItDryExecutesLS]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testItEchosBackStdoutAndStderr]' started.
Test Case '-[ProcessTests.ProcessTests testItEchosBackStdoutAndStderr]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testItEchosStderrtOnly]' started.
Test Case '-[ProcessTests.ProcessTests testItEchosStderrtOnly]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testItEchosStdoOutOnly]' started.
Test Case '-[ProcessTests.ProcessTests testItEchosStdoOutOnly]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testItExecuteLS]' started.
Test Case '-[ProcessTests.ProcessTests testItExecuteLS]' passed (0.007 seconds).
Test Case '-[ProcessTests.ProcessTests testItExecutesACommanAndHandlesErrorsdWithDummyExecutor]' started.
Test Case '-[ProcessTests.ProcessTests testItExecutesACommanAndHandlesErrorsdWithDummyExecutor]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testItExecutesACommandWithDummyExecutor]' started.
Test Case '-[ProcessTests.ProcessTests testItExecutesACommandWithDummyExecutor]' passed (0.000 seconds).
Test Case '-[ProcessTests.ProcessTests testStrayOutput]' started.
/Users/sas/Projects/GitHub/Process/Tests/ProcessTests/ProcessTests.swift:179: error: -[ProcessTests.ProcessTests testStrayOutput] : XCTAssertEqual failed: ("Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
a��") is not equal to ("Lorem ipsum dolor sit amet,
consectetur adipiscing elit,

") -
Test Case '-[ProcessTests.ProcessTests testStrayOutput]' failed (0.003 seconds).
Test Suite 'ProcessTests' failed at 2017-02-11 11:35:35.096.
         Executed 12 tests, with 1 failure (0 unexpected) in 0.012 (0.013) seconds
Test Suite 'RunTests' started at 2017-02-11 11:35:35.096
Test Case '-[ProcessTests.RunTests testExample]' started.
RunResults(exitStatus: 127, stdout: "", stderr: "/bin/sh: rbenv: command not found\nnchd.3muIAnXsE")
Test Case '-[ProcessTests.RunTests testExample]' passed (0.003 seconds).
Test Suite 'RunTests' passed at 2017-02-11 11:35:35.099.
         Executed 1 test, with 0 failures (0 unexpected) in 0.003 (0.003) seconds
Test Suite 'ProcessPackageTests.xctest' failed at 2017-02-11 11:35:35.099.
         Executed 13 tests, with 1 failure (0 unexpected) in 0.015 (0.016) seconds
Test Suite 'All tests' failed at 2017-02-11 11:35:35.099.
         Executed 13 tests, with 1 failure (0 unexpected) in 0.015 (0.017) seconds
```

Two things to note:

- the failure handler picks up stray characters `a��`
- there’s an odd line `RunResults(exitStatus: 127, stdout: "", stderr: "/bin/sh: rbenv: command not found\nnchd.3muIAnXsE”)` in there that only appears when running this test and it’s picking up something from my shell.

**Comment by finestructure** [comment]
The problem I’m having with this is that it’s not possible to reliably parse command output due to these stray characters appearing in the output.

**Comment by nsomar** [comment]
@feinstruktur Thanks so much for the failing test, I think I caught the issue. 
The string that I tried to read lacked the null termination, which meant `String` was not able to figure where to terminate the string. 

I am however not able to reproduce the issue on my machine, can you please try to apply the git diff attached here to your branch and see if it fixes it.

[fix.diff.zip](https://github.com/oarrabi/Process/files/768398/fix.diff.zip)

Please let me know if this fixes it :)

**Comment by finestructure** [comment]
Yep, I think that did it and null termination was exactly what this looked like :) I've tried this in my project and I'm not getting the junk anymore.

I still see the stray line `RunResults(exitStatus: 127, stdout: "", stderr: "/bin/sh: rbenv: command not found\n")` (now without the junk after the `\n`) in the test result output but that might actually be genuine as a result of the forced test failure?

Thank for the quick fix!

**Comment by nsomar** [comment]
I think that the \n is correct here.

Would you mind opening a PR to fix the issue? 
(I could do it but copying the test from your PR looks kinda wrong :D)

**Comment by finestructure** [comment]
The new line certainly is, I was wondering about the whole line.

Happy to open a PR first thing tomorrow morning!

-sas

--
